bear.diurnal=true
bear.breedingAge=15
bear.maxAge=70
bear.breedingProbability=0.125
bear.maxLitterSize=4
bear.creationProbability=0.03
bear.maxHealth=40
bear.foodSources=monkey

hippopotamus.diurnal=true
hippopotamus.breedingAge=25
hippopotamus.maxAge=120
hippopotamus.breedingProbability=0.12
hippopotamus.maxLitterSize=3
hippopotamus.creationProbability=0.01
hippopotamus.maxHealth=100
hippopotamus.foodSources=monkey,plant

leopard.diurnal=false
leopard.breedingAge=15
leopard.maxAge=55
leopard.breedingProbability=0.145
leopard.maxLitterSize=4
leopard.creationProbability=0.03
leopard.maxHealth=40
leopard.foodSources=sloth

monkey.diurnal=true
monkey.breedingAge=4
monkey.maxAge=40
monkey.breedingProbability=0.17
monkey.maxLitterSize=5
monkey.creationProbability=0.08
monkey.maxHealth=10
monkey.foodSources=plant

sloth.diurnal=true
sloth.breedingAge=5
sloth.maxAge=30
sloth.breedingProbability=0.17
sloth.maxLitterSize=4
sloth.creationProbability=0.08
sloth.maxHealth=8
sloth.foodSources=plant

plant.diurnal=true
plant.breedingAge=5
plant.maxAge=15
plant.breedingProbability=0.09
plant.maxLitterSize=6
plant.creationProbability=0.13
