# Population seeding order and probabilities.
# Earlier entries are checked first.

spawn.order=LION,CHEETAH,GAZELLE,JAGUAR,GRASS,ZEBRA,HUNTER
spawn.LION=0.017
spawn.CHEETAH=0.032
spawn.GAZELLE=0.2
spawn.JAGUAR=0.011
spawn.GRASS=0.55
spawn.ZEBRA=0.4998
spawn.HUNTER=0.01
