# Actor colors for the simulator view.

ui.color.GAZELLE=#FFA500
ui.color.JAGUAR=#0000FF
ui.color.CHEETAH=#FF0000
ui.color.LION=#FFC0CB
ui.color.GRASS=#00AA00
ui.color.ZEBRA=#000000
ui.color.HUNTER=#FF00FF
